### PR TITLE
Add API controllers

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
@mmoll Do you use hammer or the API at all? Any opinions here or time to test it out?

I think I covered most things.

**Comment by mmoll** [comment]
I'll test at least the GETs over the weekend and hammer support is important, however the truth is I don't have as much time as I wish and although most of the beginnings of the Salt proxy module came from me, I hardly use Salt at all personally, so we have to find more users like @bechtoldt to use our stuff ;)

**Comment by stbenjam** [comment]
@mmoll No worries :-) Just thought I'd check.. my Salt use is pretty limited myself too, I'd definitely like more "real world" users! 

There's probably a ton of users but everything is just working and they have no problems :-P

**Comment by mmoll** [comment]
:+1: from my light testing with the hammer module. Just add the .gitignore here and merge. :100:

**Comment by stbenjam** [comment]
Thanks @mmoll :palm_tree:

**Pull request merged**
