### PR TITLE
Fixes #22715 - states can't be added through API

### PR DESCRIPTION
**Pull request by L4rS6**

### CODE REVIEW

**Comment by mmoll** [comment]
@L4rS6 which foreman (core) version did you experience this problem with?

**Comment by L4rS6** [comment]
@mmoll we got the problem on version 1.15.6

**Comment by mmoll** [comment]
@L4rS6 thanks, I'll cherry-pick accordingly then.

**Comment by mmoll** [comment]
merged, danke @L4rS6!

**Pull request merged**
