### PR TITLE
add test for default derive_salt_grains behaviour

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Your ci is broken 😞

**Comment by nadjaheitmann** [comment]
Right... I wanted to fix it in #159, but I am not sure what causes it to fail in the first place. Looks like some JS dependency is not up to date.

**Comment by evgeni** [comment]
the jenkins part of things needs a new foreman-tasks release with https://github.com/theforeman/foreman-tasks/commit/cb44408841c130bbd9d5160a7cecd8aee5bd17ea in it, I'll ping the maintainers.

**Comment by evgeni** [comment]
[test foreman_salt]

**Comment by evgeni** [comment]
now it's failing on missing a `foreman_remote_execution` release with this fix: https://github.com/theforeman/foreman_remote_execution/commit/ed4250860fecb5415905d31d178d75dd84eb13fa

also pinged the maintainers

**Comment by evgeni** [comment]
[test foreman_salt]

**Comment by sbernhard** [comment]
[test foreman_salt]

**Comment by bastian-src** [comment]
Please rebase to current master:
* The NameError [here](https://ci.theforeman.org/job/foreman_salt-pull-request/228/database=postgresql,label=fast,ruby=2.5/testReport/junit/(root)/ForemanSalt__HostExtensionsTest__function%20derive_salt_grains/test_0001_host_returns_empty_hash_when_deriving_salt_grains_with_default_autosign/) has been fixed with [this](https://github.com/theforeman/foreman_salt/commit/0ff684b81940e1e63d1861e5762ef0783fcf3cd8) commit.
* The remaining test errors (related to `require_ssl_smart_proxies`) should've been fixed by [this](https://github.com/theforeman/foreman_salt/commit/33b22e7b63fc0082491c0a7436c33f884456bf37) commit. 

After a rebase, all tests run fine on my local machine. Still, the RPM problem is not fixed. Do you have any other idea which hasn't been implemented by #159 already?

**Pull request merged**
