### PR TITLE
fixes #12433 - update salt proxy from grains

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ehelms** [comment]
LGTM from a code perspective

**Comment by stbenjam** [comment]
Oh my someone reviewed a foreman_salt PR? :tada: 

Thanks :-)

**Comment by ehelms** [comment]
I'd be happy to test this from a functionality perspective if you were willing to give me steps for a basic setup or point me to me documentation to try out.

**Comment by stbenjam** [comment]
I think it's OK without functional testing, once I fix tests against master, the test here does make sure it works. 

Of course you're welcome to try it out, but it means installing a salt master and getting it up and running.  You'd just be confirming a host created by facts (salt grains) or a report creates a host, and updates the salt master.

**Comment by mmoll** [comment]
what's the status here? :)

**Comment by joberget** [comment]
Any update on this issue?

**Comment by mmoll** [comment]
this needs at least a rebase ;)

**Comment by joberget** [comment]
I am getting the following error on foreman 1.12.2:

# /usr/bin/foreman-node server
/usr/bin/foreman-node:188:in `<main>': Object#timeout is deprecated, use Timeout.timeout instead.
Could not get grains: undefined method `each_pair' for nil:NilClass

**Pull request closed without merging**
