### PR TITLE
Fix tests for Setting registry change

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by sbernhard** [comment]
[test foreman_salt]

**Comment by sbernhard** [comment]
@tbrisker can you please fix the commit message (registry vs regitery)

**Comment by tbrisker** [comment]
Whoops, fixed.

**Comment by tbrisker** [comment]
Seems failures are all from rex, tbh I'm not sure this patch is even needed. Seems the test runs with the released version of rex and not the development version that already fixed these issues, closing for now, feel free to reopen if needed after a new rex release lands.

**Pull request closed without merging**
