### PR TITLE
fixes #14273 - fix foreman compatability issues

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by mmoll** [comment]
[test] again

**Comment by stbenjam** [comment]
They'll still fail I just wanted to see them again since the jenkins job expired. There's probably more to fix, just the requires wasn't enough.  Haven't looked in depth yet.

**Comment by mmoll** [comment]
Yes, but as that routing fix went in, error messages are different now ;)

**Comment by stbenjam** [comment]
I'm totally baffled why integration tests are passing on some and failing on others :cry:

**Comment by stbenjam** [comment]
Make foreman_salt great again! :trumpet: 

This is green :green_heart:  http://ci.theforeman.org/job/test_plugin_pull_request/2755/

**Pull request merged**
