### PR TITLE
Namespace pillars under 'foreman' key

### PR DESCRIPTION
**Pull request by stbenjam**
At CfgMgmtCamp, @thatch45 mentioned we might want to namespace the pillar data from foreman under a 'foreman' key.  It makes sense, no need to pollute the root level. It is configurable, in case users are relying on the old setup.

### CODE REVIEW

**Comment by stbenjam** [comment]
[test]

**Comment by afletch** [comment]
Isn't this going to cause problems for salt formulas that are expecting pillar data to be present at the root level?

**Comment by bechtoldt** [comment]
@afletch I think the work is worth to update those formulas.

**Comment by afletch** [comment]
Really? This is going to put people off using Salt + Foreman, as the work of modifying (and maintaining modifications to) forumulas will be a significant overhead that many will consider a step too far.
If pollution really is an issue (and I'm not sure I buy into that idea), then surely a better approach would be to allow the user to configure which facts enter the root level. This avoids pollution and in one set of functionality ensures that thousands of users need not maintain hundreds of thousands of changes.

**Comment by bechtoldt** [comment]
Configuring the level might be a good approach.

However, I think we can count the number of (active?) foreman_salt users on two hands (I know only 3-4). At least there wasn't a big user feedback on this topic so far.

If such a - more or less - trivial/ simple change is causing hundreds of thousands of changes users have a bad formula design or doing something wrong.

**Comment by stbenjam** [comment]
Thanks for the feedback :-) I can change this to be off by default, but I think the option is nice, especially if you're getting pillars from other sources.

The problem in Foreman is that we're limited to string values, so how many pre-existing formulas are out there that can use that? The few I've looked at expect structured data.

I don't have any strong opinions on the topic, I don't use any complicated formulas.

**Comment by afletch** [comment]
I think the lack of foreman_salt users is down to three things, and I'm not sure namespacing Foreman pillar data by default is going to positively change those:
1 - How immature foreman_salt is as an implementation
2 - How it really is difficult to make good use of foreman+salt without pillar data. It's the missing link.
3 - How puppet-centric Foreman has historically been; but it's great to see this is changing.

@stbenjam This seems to be a common problem among configuration management systems and ENCs. It would be great if, long term, this could change, but I realise the huge task this is.

Sorry, this is going a little off-topic here. Back to the original change - it would be great if this was off by default, but even better if it was possible to decide which data made it into the root pillar.
Please keep in mind that users may have salt-managed hosts which are not foreman-managed. Having different formulas (or, tests for foreman namespaced data) to enable the two to work side-by-side is a further headache for users.

My perspective: previous Foreman user, current Salt user. Would dearly love to use them together.

**Comment by stbenjam** [comment]
>  1 - How immature foreman_salt is as an implementation

For @mmoll and I, who wrote the bulk of this, it's just for fun, so we don't really know exactly what people want who use Salt in the real world (other than better pillar data). @bechtoldt has definitely helped given us some ideas, more are welcome if you have any

>  2 - How it really is difficult to make good use of foreman+salt without pillar data. It's the missing link.

Parameters is an area of foreman that needs work, it's being tracked here: http://projects.theforeman.org/issues/4470.  I'm hopeful more of these get tackled soon, but it's hard considering it's some of the oldest code in Foreman.

Until then, I don't expect anyone to use Foreman pillars for more than a few bits of data here and there, which is why I see the value of pushing all the foreman pillars off into their own namespace.  I'd expect you'd want to use other pillar data sources for more complex use cases.

Anyway, I made this off by default, so it's there if anyone wants it.

**Comment by bechtoldt** [comment]
> Until then, I don't expect anyone to use Foreman pillars for more than a few bits 
> of data here and there, which is why I see the value of pushing all the foreman 
> pillars off into their own namespace. I'd expect you'd want to use other pillar 
> data sources for more complex use cases.

ACK

**Comment by afletch** [comment]
Bigger picture necessitates the change, understood. Thanks.

**Pull request merged**
