### PR TITLE
Fixes #24139 - add call to set_additional_attributes() of foremanl to detect virtual interfaces

### PR DESCRIPTION
**Pull request by danny-smit**
…

### CODE REVIEW

**Comment by mmoll** [comment]
@GregSutcliffe could you have a look?

**Comment by mmoll** [comment]
ok to test

**Comment by GregSutcliffe** [comment]
I'll take a look at this along with #81 tonight or tomorrow, but I can't see it doing nay harm ... @jdshewey any concerns?

**Comment by GregSutcliffe** [comment]
Per my comment in #81 (https://github.com/theforeman/foreman_salt/pull/81#issuecomment-403005661) you can see the `:virtual` attribute has appeared on my NIC - so this appears to be working :)

Merging, thanks @danny-smit!

**Pull request merged**
