### PR TITLE
Hook rake tests on test:plugins

### PR DESCRIPTION
**Pull request by lzap**
See https://github.com/theforeman/foreman/pull/3666

### CODE REVIEW

**Comment by stbenjam** [comment]
@lzap This needs a rebase as #58 was merged.  Thanks!

**Comment by lzap** [comment]
> @lzap This needs a rebase as #58 was merged.  Thanks!

Done.

-- 
Later,
 Lukas #lzap Zapletal

**Comment by stbenjam** [comment]
Set to WoC so this gets out of my taskwarrior until theforeman/foreman#3666 is merged

**Comment by sbernhard** [comment]
Looks like, other other plugins aren't using test:plugins. As there wasn't a comment since 2016, I will close this for now.

**Pull request closed without merging**
