### PR TITLE
Use first interface ip address and and fact parser test

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
@jzandbergen, please test it if possible.

**Comment by sbernhard** [comment]
[test foreman_salt]

**Comment by jzandbergen** [comment]
@sbernhard I am not familiar with ruby so I don't know how to run the test cases. But when I use this commit in my environment it works like a charm! Thanks!

**Comment by sbernhard** [comment]
@jzandbergen Hopefully, the test cases are finished soon.
Did you remove your change in smart_proxy_salt and it works just with this PR?

**Comment by jzandbergen** [comment]
@sbernhard Yes and yes.

**Pull request merged**
