### PR TITLE
Update the parser register method name

### PR DESCRIPTION
**Pull request by ares**
depends on https://github.com/theforeman/foreman/pull/2246, note that old name is still present

### CODE REVIEW

**Comment by domcleal** [comment]
You should probably set the min Foreman version, or use responds_to etc if you want cross-version compat.

**Comment by ares** [comment]
@stbenjam what do you prefer? make next foreman_salt depending on 1.8 or make it work with both? note that you can also merge this PR just before 1.9 release since without it, it will just start printing deprecation warning

**Comment by stbenjam** [comment]
foreman_salt 2.x is already released with 1.8 compatibility so I'll leave it using the deprecated method, and merge this for foreman_salt 3.x/foreman 1.9.

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
Thanks @ares, https://github.com/theforeman/foreman_salt/pull/33 bumps the version requirement to 1.9.

**Pull request merged**
