### PR TITLE
fixes #8473 - import states and environments from master

### PR DESCRIPTION
**Pull request by stbenjam**
To do:
- [x] Host/hostgroup edit page dynamic load states based on environment, like puppet classes does
- [x] Permissions
- [x] API

### CODE REVIEW

**Comment by stbenjam** [comment]
states

**Comment by ares** [comment]
@stbenjam would you be interested in helping getting https://github.com/theforeman/foreman/pull/2253 in first so we could use common parts from Environment and introduce config management system selection per host? I don't like creating separate entities for all cfgmgmt systems.

**Comment by stbenjam** [comment]
@ares  Not sure I follow, that's unrelated to this.  If environment changes to use STI, I'll make those changes in a separate commit.  But that's for 1.9.  Assuming I have the time to finish this, this feature would go into foreman_salt 2.1 for foreman 1.8.

**Comment by stbenjam** [comment]
@ares What do you need for https://github.com/theforeman/foreman/pull/2253? I'm happy to help though.

**Comment by ares** [comment]
FTR, discussed through IRC

**Pull request merged**
