### PR TITLE
Make foreman-tasks a hard requirement

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by pitr-ch** [comment]
:+1: :fireworks:

**Comment by iNecas** [comment]
This PR should address the running foreman-tasks tests with the engine tests itselves

**Comment by stbenjam** [comment]
@iNecas Thanks!!! :+1:  When will that make a foreman-tasks release?

**Comment by iNecas** [comment]
We have another feature we would like to get into the foreman-tasks, but if it's not in master by tomorrow, I will release new version without that. So the Tuesday is the answer.

**Comment by iNecas** [comment]
The new versions in a PR for foreman-packaging https://github.com/theforeman/foreman-packaging/pull/582

**Comment by iNecas** [comment]
[test]

**Pull request merged**
