### PR TITLE
Fixes #27436 - icon_path instead origin to override

### PR DESCRIPTION
**Pull request by lzap**
This needs https://github.com/theforeman/foreman/pull/6585

### CODE REVIEW

**Comment by sbernhard** [comment]
Thanks @lzap 
Will look at it after the foreman core PR was merged.

**Comment by lzap** [comment]
The core is near merging, fixed the test.

**Comment by sbernhard** [comment]
[test foreman_salt]

**Comment by ezr-ondrej** [comment]
[test foreman_salt]

**Comment by sbernhard** [comment]
Thanks @lzap

**Pull request merged**
