### PR TITLE
Fix for bug #20055

### PR DESCRIPTION
**Pull request by jdshewey**
Per http://projects.theforeman.org/issues/19266#note-14 (and confirmed by my testing) this patch resolves bug #20055

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Thanks @jdshewey. I don't think this is the right way to fix it though - there's a [dedicated helper](http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Adding-roles) for adding roles now, and we should use it so that the changes are properly future-proofed against internal changes in core.

Would be ok to update the PR? I was planning to try and look at this myself later this week, but community contributions are always awesome if you want to bag it.

(Also, we should talk about https://github.com/jdshewey/salt-formula-katello :P)

**Comment by jdshewey** [comment]
I was afraid you might ask that :( Sadly I just can't seem to get my head around Ruby and it seems to leave me miffed every time I try to pick it up. I'm afraid this is probably the best I can do - so feel free to reject this PR, or simply use it as a launching point.

But, happy to talk about my little project. Mostly, I want to be able to [fully configure Katello with the REST API,](https://github.com/jdshewey/salt-formula-katello/blob/master/_states/katello.py) but, I also wanted be able to use SALT to ensure it was installed and running first. [This script](https://github.com/jdshewey/slik-installer) is designed to quickly bootstrap the katello formula (I haven't started trying to integrate the [freeipa formula](https://github.com/salt-formulas/salt-formula-freeipa) just yet) and there are still several REST calls that need to be added. So it is definitely still in the early stages and very much a work in progress. You can E-mail me at jdshewey at gmail dot com or we could chat on IRC if you are interested.

**Comment by GregSutcliffe** [comment]
I feel the same about Python, which leaves me a little adrift in my new learnings of the Salt world :P. Fair enough though, and thanks for the starting point. I can probably fix the code, so I'll add a commit here when I have a chance and you can see if it fixes your test system too.

I'll ping you on the other stuff, it doesn't really belong here ;)

**Comment by mmoll** [comment]
@GregSutcliffe was there any progress here?

**Comment by GregSutcliffe** [comment]
@mmoll sadly no, my time is super busy with infra stuff at the moment. I guess we could merge this as a temporary fix for 1.16...

**Comment by mmoll** [comment]
allright, merged, thanks @jdshewey!

**Comment by GregSutcliffe** [comment]
@mmoll can you make sure #20055 stays open, or open a new one for a proper fix?

**Comment by mmoll** [comment]
I used "Refs" for exactly that point 😹

**Comment by mmoll** [comment]
8.0.3 (for Foreman 1.15) and 9.0.0 (for Foreman 1.16) got released with this fix.

**Comment by GregSutcliffe** [comment]
@mmoll awesome, sorry, didn't click the commit to see the final message. Nice one! @jdshewey thanks for the contribution!

**Comment by jdshewey** [comment]
@mmoll @GregSutcliffe - I'm not currently seeing this change in 1.16.0.

**Comment by mmoll** [comment]
https://github.com/theforeman/foreman-packaging/pull/1961

**Pull request merged**
